### ISSUE TITLE
Wallet unable to connect to peers

### ISSUE THREAD

**Issue by geoffreyn** [HashEngineering/quarkcoin-wallet#1]
Could be related to a previous fork.

Most likely due to none of the peers being valid anymore.  Here are some which I'm able to connect to through quarkcoind:

"91.232.105.11",
"96.18.144.46",
"109.236.85.42",
"109.236.85.42",
"192.241.151.155",
"213.136.75.175",
"109.74.215.171"

**Comment by HashEngineering** [comment]
An update was posted to Google Play.  The source code will be updated here soon.
